### ISSUE TITLE
feature request : possible pitches set

### ISSUE THREAD

**Issue by vichug** [CircuitMusicLabs/petra#29]
hey, it would be cool if it were possible to send a list of different pitch and have the granulation transposition process randomly choose between those pitches, rather than find any pitch in a given range, this way you could have a sort of granular chord. Wouldn't it ? :)

**Comment by CircuitMusicLabs** [comment]
That would indeed be something to consider. Sounds very interesting. I'll investigate this and put it in the wishlist. I don't have such a thing as a roadmap, however, so I can't tell you when this is going to happen. But thanks so much for the input. I'll leave this issue open for the time being.

**Comment by CircuitMusicLabs** [comment]
I know it's been a while (a long while), but I now have a first version of the feature you requested. Would you be willing to test? If so, I have compiled and pushed the externals in the pitchlist branch.
Edit: Mac only atm, sorry!

**Comment by CircuitMusicLabs** [comment]
I have now also recompiled the windows externals.
And a bit of explaining: You can now send the objects the "pitchlist" message, followed by a maximum number of 10 float values. Values below zero will be set to one. Values above 8 will be set to 8. Sending the "pitchlist" message followed by a zero (0) will disable reading pitch values from the stored list and continue reading the values from the pitch min/max inlets.

**Comment by vichug** [comment]
Hey there, didn't see the notification of answer, i would be very willing to test :) will look at it !

**Comment by CircuitMusicLabs** [comment]
Hey, no problem at all! Just download the latest release (1.1.4-beta). I've updated all the documentation and help files.

**Comment by vichug** [comment]
hey, it's been a while, but so far it works beautifully ! thanks !
